import {
  ChatBubbleLeftEllipsisIcon,
  PhoneIcon,
} from "@heroicons/react/24/outline";
import { StarIcon } from "@heroicons/react/24/solid";
import { type NextPage } from "next";
import Head from "next/head";
import CarBottom from "~/components/car-details/CarBottom";
import CarNav from "~/components/car-details/CarNav";

const Car: NextPage = () => {
  return (
    <>
      <Head>
        <title>Honda Civic</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CarNav />
      <main className="layout-1 mt-2 min-h-screen bg-base-100">
        <img
          src={"/car-1.jpg"}
          className="h-full w-full rounded-md bg-cover bg-center shadow-lg duration-100"
        />
        {/* select images */}
        <div className="justify-content mt-2 flex gap-x-2 overflow-x-auto">
          <img
            src={"/car-1.jpg"}
            className="h-20 w-20 rounded-md bg-cover bg-center shadow-lg duration-100"
          />
          <img
            src={"/car-1.jpg"}
            className="h-20 w-20 rounded-md bg-cover bg-center shadow-lg duration-100"
          />
          <img
            src={"/car-1.jpg"}
            className="h-20 w-20 rounded-md bg-cover bg-center shadow-lg duration-100"
          />
          <img
            src={"/car-1.jpg"}
            className="h-20 w-20 rounded-md bg-cover bg-center shadow-lg duration-100"
          />
          <img
            src={"/car-1.jpg"}
            className="h-20 w-20 rounded-md bg-cover bg-center shadow-lg duration-100"
          />
          <img
            src={"/car-1.jpg"}
            className="h-20 w-20 rounded-md bg-cover bg-center shadow-lg duration-100"
          />
          <img
            src={"/car-1.jpg"}
            className="h-20 w-20 rounded-md bg-cover bg-center shadow-lg duration-100"
          />
        </div>

        <h1 className="mt-4 text-xl font-bold text-primary">Honda Civic</h1>

        <p className="base-content text-justify">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum dolore,
          odit blanditiis autem obcaecati similique consectetur, ad sapiente
          tenetur laboriosam culpa natus nostrum esse facilis modi, unde nihil
          ut aut.{" "}
        </p>

        <div className="mt-6 flex items-center rounded-md bg-neutral px-2 py-3 shadow-lg">
          {/* vendor pic */}

          <label tabIndex={0} className="btn-ghost btn-circle avatar btn ">
            <div className="w-10 rounded-full">
              <img src="/profile.jpeg" />
            </div>
          </label>

          {/* vendor info */}
          <div className="ml-2 grid w-3/5 text-neutral-content">
            <span className="font-bold">Ricardo Menotti</span>
            <span className="flex">
              <StarIcon className="w-5 text-yellow-300" />
              4.5
            </span>
          </div>
          <div className="flex justify-between text-neutral-content">
            <div className="p-2">
              <PhoneIcon className="w-6" />
            </div>
            <div className="p-2">
              <ChatBubbleLeftEllipsisIcon className="w-6" />
            </div>
          </div>
        </div>

        {/* detalles tecnicos */}
        <div className="mt-4">
          <h3 className="font-medium text-lg">Descripcion Tecnica:</h3>
        </div>
      </main>
      <CarBottom />
    </>
  );
};

export default Car;
