import { type NextPage } from "next";
import Head from "next/head";

const New: NextPage = () => {
  return (
    <>
      <Head>
        <title>Publicar</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-base-100">publicar</main>
    </>
  );
};

export default New;
