import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import BottomTabs from "~/components/BottomTabs";
import FillInfo from "~/components/new-car/FillInfo";
import SelectImages from "~/components/new-car/SelectImages";
import SelectPlan from "~/components/new-car/SelectPlan";

const New: NextPage = () => {
  const [step, setStep] = useState(0);
  const [carId, setCarId] = useState("");
  const handleNext = (id?: string) => {
    setStep((step) => step + 1);
    if (id) {
      setCarId(id);
    }
  };
  console.log(carId)
  return (
    <>
      <Head>
        <title>Publicar Anuncio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-base-100">
        {/* steps */}

        <div className="mt-4 flex items-center justify-center">
          <ul className="steps w-full">
            <li
              className={`${step >= 0 ? "step-primary" : ""} step`}
              onClick={() => setStep(0)}
            >
              Plan
            </li>
            <li className={`${step >= 1 ? "step-primary" : ""} step`}>
              Imagenes
            </li>
            <li className={`${step >= 2 ? "step-primary" : ""} step`}>
              Descripcion
            </li>
            <li className={`${step >= 3 ? "step-primary" : ""} step`}>
              Review
            </li>
          </ul>
        </div>

        <div className="layout-1 mt-6">
          {step === 0 && <SelectPlan next={handleNext} />}
          {step === 1 && <SelectImages next={handleNext} />}
          {step === 2 && <FillInfo next={handleNext} carId={carId}/>}
        </div>
      </main>
      <BottomTabs />
    </>
  );
};

export default New;
